"""Add password_hash field to schools table

Revision ID: 27993df518ad
Revises: cfe883d06dbe
Create Date: 2025-11-22 03:59:23.753207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27993df518ad'
down_revision: Union[str, None] = 'cfe883d06dbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('password_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schools', 'password_hash')
    # ### end Alembic commands ###
