"""Add password_hash field to parents table

Revision ID: cfe883d06dbe
Revises: 9b23d9c281a2
Create Date: 2025-11-22 03:45:01.748271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfe883d06dbe'
down_revision: Union[str, None] = '9b23d9c281a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parents', sa.Column('password_hash', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parents', 'password_hash')
    # ### end Alembic commands ###
