"""add_public_id_to_study_materials

Revision ID: e0950f3adad2
Revises: 01391b2ffaa2
Create Date: 2025-11-22 09:41:40.221822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0950f3adad2'
down_revision: Union[str, None] = '01391b2ffaa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_materials', sa.Column('public_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_materials', 'public_id')
    # ### end Alembic commands ###
